services:
  - type: web
    name: routex-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GEMINI_API_KEY_4
        sync: false
      - key: GEMINI_API_KEY_5
        sync: false
      - key: GEMINI_API_KEY_6
        sync: false
      - key: GEMINI_API_KEY_7
        sync: false
      - key: GEMINI_API_KEY_8
        sync: false
      - key: GEMINI_API_KEY_9
        sync: false
      - key: GEMINI_API_KEY_10
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_KEY_2
        sync: false
